FROM ros1_slam_base
SHELL ["/bin/bash", "-c"]

# Setup locale
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV ROS2_WORKSPACE=/root/ROS/ros2_ws
ENV SLAM_ROS2=${ROS2_WORKSPACE}/src/ros2_orbslam3/
ARG ROS2_DISTRO=foxy

# Setup keys and sources
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu \
    $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'

# Install ROS2 packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    ros-${ROS2_DISTRO}-ros-base \
    ros-${ROS2_DISTRO}-rviz2 \
    ros-${ROS2_DISTRO}-ros2cli \
    ros-${ROS2_DISTRO}-ros2topic \
    ros-${ROS2_DISTRO}-rqt* \
    ros-${ROS2_DISTRO}-message-filters \
    ros-${ROS2_DISTRO}-rclcpp \
    libsystemd-dev \
    python3-colcon-common-extensions

# TODO: Add rest of depends -if- and clean
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy from local
COPY ./ROS/ros2_ws/src/ros2_orbslam3 ${SLAM_ROS2}

# Build ROS 2 packages
WORKDIR ${ROS2_WORKSPACE}
RUN source /opt/ros/${ROS2_DISTRO}/setup.bash && colcon build --symlink-install

# Copy the workspace setup file
COPY ./docker/ros_entrypoint.sh /
CMD ["/ros_entrypoint.sh"]
